# Generated by Django 5.0.3 on 2024-05-08 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_goallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
