# Generated by Django 5.0.3 on 2024-05-28 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
