# Generated by Django 5.0.3 on 2024-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_goals_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='orgId',
            field=models.IntegerField(default=1),
        ),
    ]
