# Generated by Django 5.0.3 on 2024-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_goallog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goallist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
