# Generated by Django 5.0.3 on 2024-05-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_goallist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goallist',
            name='goal',
        ),
        migrations.AddField(
            model_name='goallist',
            name='goals',
            field=models.ManyToManyField(related_name='goal_lists', to='api.goallog'),
        ),
    ]
