# Generated by Django 5.0.3 on 2024-05-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_goallist_goal_goallist_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goallist',
            name='goals',
        ),
        migrations.AddField(
            model_name='goallist',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.goallog'),
            preserve_default=False,
        ),
    ]
